apiVersion: apps/v1
kind: Deployment
metadata:
  name: getdbdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getdb
  template:
    metadata:
      labels:
        app: getdb
    spec:
      terminationGracePeriodSeconds : 3
      containers:
      - name: getdb
        image: "localhost:32000/01getdb:vs07"
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8001"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pre1dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre1

  template:
    metadata:
      labels:
        app: pre1
    spec:
      terminationGracePeriodSeconds : 3
      containers:
      - name: pre1
        image: "desg2022/02pre1:vs01"
        env:
          - name: "PORT"
            value: "8002"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "4000m"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insertdbdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insertdb
  template:
    metadata:
      labels:
        app: insertdb
    spec:
      terminationGracePeriodSeconds : 8
      containers:
      - name: insertdb
        image: "localhost:32000/03insertdb:vs06"
        env:
          - name: "PORT"
            value: "8003"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "4000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mecabdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mecab
  template:
    metadata:
      labels:
        app: mecab
    spec:
      terminationGracePeriodSeconds : 3
      containers:
      - name: mecab
        image: "desg2022/04mecab:vs02"
        env:
          - name: "PORT"
            value: "8004"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "4000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pndp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pn
  template:
    metadata:
      labels:
        app: pn
    spec:
      terminationGracePeriodSeconds : 3
      containers:
      - name: pn
        image: "desg2022/05pn:vs01"
        env:
          - name: "PORT"
            value: "8005"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "4000m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      terminationGracePeriodSeconds : 3
      containers:
      - name: cat
        image: "localhost:32000/07catlocal:vs01"
        env:
          - name: "PORT"
            value: "8001"
        resources:
          requests:
            memory: "8096Mi"
            cpu: "8000m"

       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postneralldp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postnerall
  template:
    metadata:
      labels:
        app: postnerall
    spec:
      terminationGracePeriodSeconds : 10
      containers:
      - name: postnerall
        image: "desg2022/10postnerall1214:vs07"
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8010"
        resources:
          requests:
            memory: "8G"
            cpu: "8000m"

