apiVersion: apps/v1
kind: Deployment
metadata:
  name: postnerall2dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postnerall2
  template:
    metadata:
      labels:
        app: postnerall2
    spec:
      containers:
      - name: postnerall2
        image: localhost:32000/11postnerall:vs02
        imagePullPolicy: Always
        env:
          - name: "PORT"
            value: "8010"
---
---
apiVersion: v1
kind: Service
metadata:
  name: postnerall2-lb
spec:
  type: LoadBalancer
  selector:
    app: postnerall2
  ports:
  - protocol: TCP
    port: 8010 
    targetPort: 8010
    nodePort: 30211